services:
  mongo1:
    image: mongo:7.0 # Use the latest version of MongoDB
    command: [
      "--replSet", "rs0", # Set the replica set name
      "--bind_ip_all", # Allow connections from all network interfaces, including the host machine, to the container
      "--port", "27017", # Set the port number
      '--auth', # Enable authentication
    ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: toto # Set the root username
      MONGO_INITDB_ROOT_PASSWORD: toto # Set the root password
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allow the container to access the host machine
    healthcheck: # Check the health of the container
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s # Check the health of the container every 5 seconds
      timeout: 30s # Wait for 30 seconds before considering the container unhealthy
      start_period: 0s # Start checking the health of the container immediately
      retries: 30 # Retry checking the health of the container 30 times
    volumes:
      - "mongo1_data:/data/db" # Mount the data directory to the container volume 
      - "mongo1_config:/data/configdb" # Mount the config directory to the container volume
volumes:
  mongo1_data:
  mongo1_config: